baseURL = "https://was-up.github.io/"
languageCode = "en-us"
title = "WASUP"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsStyle = "dracula"

[params]
    subtitle = "Wednesday Afternoon Support for the Uninformed Pupil"
    mode = "dark"
    disableDisqusTypes = ["page", "post"]
