baseURL = "https://was-up.github.io/"
languageCode = "en-us"
title = "WASUP"
theme = "was-up.ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsStyle = "dracula"

[params]
    subtitle = "Wednesday Afternoon Support for the Uninformed Pupil"
    mode = "dark"
    disableDisqusTypes = ["projects", "publications"]
    customCSS = "css/was-up.css"
    customJS = [ "js/citation.min.js", "js/was-up.js"  ]

[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/was-up/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 3